# Navigation Links
#   The weight parameter defines the order that the links will appear in.
# header 的菜单
main:
  - name: 首页
    url: /
    weight: 10
  - name: 文档
    url: docs/
    weight: 20
  - name: 博客
    url: blog/
    weight: 30
  # - name: 案例
  #   url: showcase/
  #   weight: 40
  # - name: 社区
  #   url: community/
  #   weight: 50

#sidebar:
  # - identifier: more
  #   name: Still need help?
  #   params:
  #     type: separator
  #   weight: 1
  # - identifier: community
  #   name: "Community"
  #   pageRef: "/community"
  #   weight: 2
  # - identifier: hugoDocs
  #   name: "Hugo Docs ↗"
  #   url: "https://docs.hugoblox.com"
  #   weight: 3
